monitor.bluez.properties = {
  # RE-ENABLE SYNC: This links logical and hardware volume
  "bluez5.enable-hw-volume": true,
  
  # Keep these for mic stability in Vesktop
  "bluez5.roles": [ "a2dp_sink", "a2dp_source", "hfp_hf", "hfp_ag" ],
  "bluez5.codecs": [ "msbc", "sbc", "cvsd" ],
  "bluez5.autoswitch-to-headset-profile": true
}
