-- Database plugin (disabled due to vim.pack compatibility issue)
-- vim.pack.add({
--   { src = "https://github.com/kndndrj/nvim-dbee" },
-- })
-- vim.pack.add({
--   { src = "https://github.com/MunifTanjim/nui.nvim" },
-- })
--
-- require("lazyload").on_vim_enter(function()
--   vim.cmd("packadd nvim-dbee")
--   vim.cmd("packadd nui.nvim")
--   require("dbee").setup()
--
--   vim.keymap.set("n", "<leader>bt", function() require("dbee").toggle() end, { desc = "DBee: Toggle UI" })
--   vim.keymap.set("n", "<leader>be", function() require("dbee").execute() end, { desc = "DBee: Execute Query" })
--   vim.keymap.set("n", "<leader>bs", function() require("dbee").sidebar_toggle() end, { desc = "DBee: Toggle Sidebar" })
--   vim.keymap.set("n", "<leader>ba", function() require("dbee").execute() end, { desc = "DBee: Action (Execute)" })
--   vim.keymap.set("n", "<leader>bq", function() require("dbee").close() end, { desc = "DBee: Quit/Close" })
-- end)