[main]
# Fonts with fallbacks are defined in a comma-separated list
font=Maple Mono:size=16, Nerd Font Symbols:size=11, FreeSans:size=16, Arial:size=16

# Most Linux distributions install Foot's default themes here.
# This automatically loads the Rosé Pine Moon color palette.
include=/usr/share/foot/themes/rose-pine-moon

[colors-dark]
# This handles the window_background_opacity setting
alpha=0.6
