[options]
# Review changes before installing
UpgradeMenu
# Check for updates in -git/devel packages
Devel
# Look for AUR packages providing dependencies
Provides
# Shows repo and AUR updates in one list
CombinedUpgrade
# Periodically call sudo to prevent timeout
SudoLoop
# Remove build files after a successful install
CleanAfter
# Enable building in a clean chroot environment
Chroot

[bin]
# Use bat for syntax-highlighted PKGBUILD reviews
Pager = bat
