# Expressoft yazi theme
# : Manager {{{

[manager]
cwd = { fg = "#449c99" }

# Hovered
hovered         = { fg = "#739c44", bg = "#372b20" }
preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "#9c6d44", italic = true }
find_position = { fg = "#766454", bg = "reset", italic = true }

# Marker
marker_selected = { fg = "#9c6d44", bg = "#9c6d44" }
marker_copied   = { fg = "#9c6d44", bg = "#9c6d44" }
marker_cut      = { fg = "#9c4473", bg = "#9c4473" }

# Tab
tab_active   = { fg = "#8f7c6d", bg = "#241b13" }
tab_inactive = { fg = "#cabeb3", bg = "#241b13" }
tab_width    = 1

# Border
border_symbol = "│"
border_style  = { fg = "#aa998b" }

# : Status {{{

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#aa998b", bg = "#241b13" }

# Mode
mode_normal = { fg = "#739c44", bg = "#241b13", bold = true }
mode_select = { fg = "#9c4473", bg = "#241b13", bold = true }
mode_unset  = { fg = "#9c6d44", bg = "#241b13", bold = true }

# Progress
progress_label  = { fg = "#cabeb3", bold = true }
progress_normal = { fg = "#8f7c6d", bg = "#372b20" }
progress_error  = { fg = "#9c4473", bg = "#372b20" }

# Permissions
permissions_t = { fg = "#8f7c6d" }
permissions_r = { fg = "#9c6d44" }
permissions_w = { fg = "#9c4473" }
permissions_x = { fg = "#6d449c" }
permissions_s = { fg = "#739c44" }

# : }}}


# : Input {{{

[input]
border   = { fg = "#cabeb3" }
title    = {}
value    = {}
selected = { reversed = true }

# : }}}


# : Select {{{

[select]
border   = { fg = "#739c44" }
active   = { fg = "#4b3c2e" }
inactive = {}

# : }}}


# : Tasks {{{

[tasks]
border  = { fg = "#aa998b" }
title   = {}
hovered = { underline = true }

# : }}}


# : Which {{{

[which]
mask            = { bg = "#241b13" }
cand            = { fg = "#449c99" }
rest            = { fg = "#4b3c2e" }
desc            = { fg = "#9c6d44" }
separator       = "  "
separator_style = { fg = "#cabeb3" }

# : }}}


# : Help {{{

[help]
on      = { fg = "#9c6d44" }
exec    = { fg = "#449c99" }
desc    = { fg = "#8f7c6d" }
hovered = { bg = "#cabeb3", bold = true }
footer  = { fg = "#739c44", bg = "#4b3c2e" }

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#449c99" },

    # Videos
    { mime = "video/*", fg = "#9c6d44" },
    { mime = "audio/*", fg = "#9c6d44" },

    # Archives
    { mime = "application/zip",             fg = "#449c6d" },
    { mime = "application/gzip",            fg = "#449c6d" },
    { mime = "application/x-tar",           fg = "#449c6d" },
    { mime = "application/x-bzip",          fg = "#449c6d" },
    { mime = "application/x-bzip2",         fg = "#449c6d" },
    { mime = "application/x-7z-compressed", fg = "#449c6d" },
    { mime = "application/x-rar",           fg = "#449c6d" },

    # Fallback
    { name = "*", fg = "#aa998b" },
    { name = "*/", fg = "#739c44" }
]

# : }}}
