[mgr]
marker_symbol = "󰄲 "
show_hidden = true
sort_by = "mtime"
sort_dir_first = true
scrolloff = 8
[input]
cursor_blink = true
[plugin]
prepend_previewers = [
    # Archive previewer
    { mime = "application/*zip", run = "ouch" },
    { mime = "application/x-tar", run = "ouch" },
    { mime = "application/x-bzip2", run = "ouch" },
    { mime = "application/x-7z-compressed", run = "ouch" },
    { mime = "application/x-rar", run = "ouch" },
    { mime = "application/vnd.rar", run = "ouch" },
    { mime = "application/x-xz", run = "ouch" },
    { mime = "application/xz", run = "ouch" },
    { mime = "application/x-zstd", run = "ouch" },
    { mime = "application/zstd", run = "ouch" },
    { mime = "application/java-archive", run = "ouch" },
]
[opener]
extract = [
    { run = 'ouch d -y %s', desc = "Extract here with ouch", for = "windows" },
    { run = 'ouch d -y %s', desc = "Extract here with ouch", for = "unix" },
]
play = [
    { run = 'mpv %s', orphan = true, for = "unix" },
    { run = '"C:\Program Files\mpv.exe" %s', orphan = true, for = "windows" },
]
edit = [
    { run = '$EDITOR %s', block = true, for = "unix" },
    { run = "%EDITOR% %s", block = true, for = "windows" },
]
pdf_opener = [
    { run = 'zathura %s', block = false, desc = "Open with Zathura" },
]

[open]
prepend_rules = [
    { url = "*.pdf", mime = "application/pdf", use = "pdf_opener" },
]