# Fuzzel - Rosé Pine Moon Theme
font=Cartograph CF:size=12
prompt="❯ "
icon-theme=Papirus
terminal=foot
padding-horizontal=5
padding-vertical=5
lines=15
width=30
horizontal-pad=5

[colors]
# bg: #232136 | fgd: #e0def4 | cya: #9ccfd8 | grn: #3e8fb0 | ora: #ea9a97
background=232136ff
text=e0def4ff
match=9ccfd8ff
selection=3e8fb0ff
selection-text=232136ff
selection-match=9ccfd8ff
border=ea9a97ff

[border]
width=3
radius=6
