return {
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	opts = {
		ensure_installed = {
			"lua",
			"vimdoc",
			"javascript",
			"markdown",
			"typescript",
			"c",
			"vim",
			"html",
			"luadoc",
			"markdown_inline",
			"css",
			"json",
			"php",
			"bash",
		},
		auto_install = true,
		highlight = { enable = true, additional_vim_regex_highlighting = false },
		indent = { enable = true },
	},
}
