-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then vim.cmd('highlight clear') end
vim.g.colors_name = "expressoft.lua"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@attribute", { link = "TSAttribute" })
hi(0, "@attribute.builtin", { link = "Special" })
hi(0, "@boolean", { link = "TSBoolean" })
hi(0, "@character", { link = "TSCharacter" })
hi(0, "@character.special", { link = "SpecialChar" })
hi(0, "@class", { link = "TSType" })
hi(0, "@comment", { link = "TSComment" })
hi(0, "@comment.error", { link = "@text.danger" })
hi(0, "@comment.hint", { link = "DiagnosticHint" })
hi(0, "@comment.info", { link = "DiagnosticInfo" })
hi(0, "@comment.note", { link = "DiagnosticInfo" })
hi(0, "@comment.todo", { link = "@text.todo" })
hi(0, "@comment.warning", { link = "@text.warning" })
hi(0, "@conditional", { link = "TSConditional" })
hi(0, "@constant", { link = "TSConstant" })
hi(0, "@constant.builtin", { link = "TSConstant" })
hi(0, "@constant.macro", { link = "TSConstant" })
hi(0, "@constructor", { link = "TSConstructor" })
hi(0, "@debug", { link = "Debug" })
hi(0, "@decorator", { link = "Identifier" })
hi(0, "@define", { link = "Define" })
hi(0, "@diff.delta", { link = "DiffChange" })
hi(0, "@diff.minus", { link = "@text.diff.delete" })
hi(0, "@diff.plus", { link = "@text.diff.add" })
hi(0, "@enum", { link = "TSType" })
hi(0, "@enumMember", { link = "Constant" })
hi(0, "@error", { link = "TSError" })
hi(0, "@event", { link = "Identifier" })
hi(0, "@exception", { link = "TSException" })
hi(0, "@field", { link = "TSField" })
hi(0, "@float", { link = "TSFloat" })
hi(0, "@function", { link = "TSFunction" })
hi(0, "@function.builtin", { link = "TSFuncBuiltin" })
hi(0, "@function.call", { link = "TSFunction" })
hi(0, "@function.macro", { link = "TSFuncMacro" })
hi(0, "@function.method", { link = "@method" })
hi(0, "@function.method.call", { link = "@method.call" })
hi(0, "@include", { link = "TSInclude" })
hi(0, "@interface", { link = "Structure" })
hi(0, "@keyword", { link = "TSKeyword" })
hi(0, "@keyword.conditional", { link = "@conditional" })
hi(0, "@keyword.debug", { link = "@debug" })
hi(0, "@keyword.directive", { link = "@preproc" })
hi(0, "@keyword.directive.define", { link = "@define" })
hi(0, "@keyword.exception", { link = "@exception" })
hi(0, "@keyword.function", { link = "TSKeywordFunction" })
hi(0, "@keyword.import", { link = "@include" })
hi(0, "@keyword.operator", { link = "TSKeywordOperator" })
hi(0, "@keyword.repeat", { link = "@repeat" })
hi(0, "@keyword.return", { link = "TSKeyword" })
hi(0, "@keyword.storage", { link = "@storageclass" })
hi(0, "@label", { link = "TSLabel" })
hi(0, "@lsp.mod.deprecated", { link = "DiagnosticDeprecated" })
hi(0, "@lsp.type.class", { link = "@type" })
hi(0, "@lsp.type.comment", { link = "@comment" })
hi(0, "@lsp.type.decorator", { link = "@function" })
hi(0, "@lsp.type.enum", { link = "@type" })
hi(0, "@lsp.type.enumMember", { link = "@constant" })
hi(0, "@lsp.type.event", { link = "@type" })
hi(0, "@lsp.type.function", { link = "@function" })
hi(0, "@lsp.type.interface", { link = "@type" })
hi(0, "@lsp.type.keyword", { link = "@keyword" })
hi(0, "@lsp.type.macro", { link = "@function.macro" })
hi(0, "@lsp.type.method", { link = "@method" })
hi(0, "@lsp.type.modifier", { link = "@type.qualifier" })
hi(0, "@lsp.type.namespace", { link = "@namespace" })
hi(0, "@lsp.type.number", { link = "@number" })
hi(0, "@lsp.type.operator", { link = "@operator" })
hi(0, "@lsp.type.parameter", { link = "@parameter" })
hi(0, "@lsp.type.property", { link = "@property" })
hi(0, "@lsp.type.regexp", { link = "@string.regexp" })
hi(0, "@lsp.type.string", { link = "@string" })
hi(0, "@lsp.type.struct", { link = "@type" })
hi(0, "@lsp.type.type", { link = "@type" })
hi(0, "@lsp.type.typeParameter", { link = "@type.definition" })
hi(0, "@lsp.type.variable", { link = "@variable" })
hi(0, "@markup.heading", { link = "@text.title" })
hi(0, "@markup.italic", { link = "Italic" })
hi(0, "@markup.link", { link = "@text.reference" })
hi(0, "@markup.link.label", { link = "@string.special" })
hi(0, "@markup.link.url", { link = "@text.uri" })
hi(0, "@markup.list", { link = "@punctuation.special" })
hi(0, "@markup.raw", { link = "@text.literal" })
hi(0, "@markup.strikethrough", { link = "@text.strikethrough" })
hi(0, "@markup.strong", { link = "@text.strong" })
hi(0, "@method", { link = "TSMethod" })
hi(0, "@method.call", { link = "TSMethod" })
hi(0, "@modifier", { link = "Identifier" })
hi(0, "@module", { link = "@namespace" })
hi(0, "@module.builtin", { link = "Special" })
hi(0, "@namespace", { link = "TSNamespace" })
hi(0, "@none", { link = "TSNone" })
hi(0, "@number", { link = "TSNumber" })
hi(0, "@number.float", { link = "@float" })
hi(0, "@operator", { link = "TSOperator" })
hi(0, "@parameter", { link = "TSParameter" })
hi(0, "@preproc", { link = "PreProc" })
hi(0, "@property", { link = "TSProperty" })
hi(0, "@punctuation.bracket", { link = "TSPunctBracket" })
hi(0, "@punctuation.delimiter", { link = "TSPunctDelimiter" })
hi(0, "@punctuation.special", { link = "TSPunctSpecial" })
hi(0, "@regexp", { link = "TSStringRegex" })
hi(0, "@repeat", { link = "TSRepeat" })
hi(0, "@storageclass", { link = "StorageClass" })
hi(0, "@string", { link = "TSString" })
hi(0, "@string.escape", { link = "TSStringEscape" })
hi(0, "@string.regex", { link = "TSStringRegex" })
hi(0, "@string.regexp", { link = "@string.regex" })
hi(0, "@string.special", { link = "SpecialChar" })
hi(0, "@string.special.symbol", { link = "@symbol" })
hi(0, "@string.special.url", { link = "@text.uri" })
hi(0, "@struct", { link = "TSType" })
hi(0, "@symbol", { link = "TSSymbol" })
hi(0, "@tag", { link = "TSTag" })
hi(0, "@tag.attribute", { link = "TSAttribute" })
hi(0, "@tag.builtin", { link = "Special" })
hi(0, "@tag.delimiter", { link = "TSTagDelimiter" })
hi(0, "@text", { link = "TSText" })
hi(0, "@text.danger", { link = "DiagnosticError" })
hi(0, "@text.diff.add", { link = "DiffAdd" })
hi(0, "@text.diff.delete", { link = "DiffDelete" })
hi(0, "@text.emphasis", { link = "TSEmphasis" })
hi(0, "@text.environment", { link = "Macro" })
hi(0, "@text.environment.name", { link = "Type" })
hi(0, "@text.literal", { link = "TSLiteral" })
hi(0, "@text.math", { link = "Number" })
hi(0, "@text.note", { link = "Tag" })
hi(0, "@text.reference", { link = "TSParameterReference" })
hi(0, "@text.strike", { link = "TSStrike" })
hi(0, "@text.strong", { link = "TSStrong" })
hi(0, "@text.title", { link = "TSTitle" })
hi(0, "@text.todo", { link = "Todo" })
hi(0, "@text.underline", { link = "TSUnderline" })
hi(0, "@text.uri", { link = "TSURI" })
hi(0, "@text.warning", { link = "DiagnosticWarn" })
hi(0, "@type", { link = "TSType" })
hi(0, "@type.builtin", { link = "TSTypeBuiltin" })
hi(0, "@type.definition", { link = "TSType" })
hi(0, "@type.qualifier", { link = "TSKeyword" })
hi(0, "@typeParameter", { link = "Type" })
hi(0, "@variable", { link = "TSVariable" })
hi(0, "@variable.builtin", { link = "TSVariableBuiltin" })
hi(0, "@variable.member", { link = "@field" })
hi(0, "@variable.parameter", { link = "@parameter" })
hi(0, "@variable.parameter.builtin", { link = "Special" })
hi(0, "Bold", { bold = true })
hi(0, "Boolean", { fg = "#44479c" })
hi(0, "Character", { fg = "#44739c" })
hi(0, "CmpDocumentation", { bg = "#120d09", fg = "#8f7c6d" })
hi(0, "CmpDocumentationBorder", { bg = "#120d09", fg = "#8f7c6d" })
hi(0, "CmpItemAbbr", { bg = "#241b13", fg = "#8f7c6d" })
hi(0, "CmpItemAbbrDeprecated", { fg = "#4b3c2e", strikethrough = true })
hi(0, "CmpItemAbbrMatch", { fg = "#739c44" })
hi(0, "CmpItemAbbrMatchFuzzy", { fg = "#739c44" })
hi(0, "CmpItemKindClass", { fg = "#6d449c" })
hi(0, "CmpItemKindConstant", { fg = "#44479c" })
hi(0, "CmpItemKindConstructor", { fg = "#739c44" })
hi(0, "CmpItemKindDefault", { fg = "#8f7c6d" })
hi(0, "CmpItemKindEnum", { fg = "#6d449c" })
hi(0, "CmpItemKindEnumMember", { fg = "#6d449c" })
hi(0, "CmpItemKindEvent", { fg = "#6d449c" })
hi(0, "CmpItemKindField", { fg = "#44739c" })
hi(0, "CmpItemKindFunction", { fg = "#739c44" })
hi(0, "CmpItemKindInterface", { fg = "#6d449c" })
hi(0, "CmpItemKindKeyword", { fg = "#449c6d" })
hi(0, "CmpItemKindMethod", { fg = "#739c44" })
hi(0, "CmpItemKindModule", { fg = "#8f7c6d" })
hi(0, "CmpItemKindOperator", { fg = "#8f7c6d" })
hi(0, "CmpItemKindProperty", { fg = "#44739c" })
hi(0, "CmpItemKindReference", { fg = "#44739c" })
hi(0, "CmpItemKindSnippet", { fg = "#766454" })
hi(0, "CmpItemKindStruct", { fg = "#6d449c" })
hi(0, "CmpItemKindTypeParameter", { fg = "#6d449c" })
hi(0, "CmpItemKindUnit", { fg = "#6d449c" })
hi(0, "CmpItemKindValue", { fg = "#44479c" })
hi(0, "CmpItemKindVariable", { fg = "#44739c" })
hi(0, "CmpItemMenu", { fg = "#766454" })
hi(0, "ColorColumn", { bg = "#241b13" })
hi(0, "Comment", { fg = "#4b3c2e" })
hi(0, "Conceal", { bg = "#120d09", fg = "#739c44" })
hi(0, "Conditional", { fg = "#449c6d" })
hi(0, "Constant", { fg = "#44479c" })
hi(0, "Cursor", { bg = "#8f7c6d", fg = "#120d09" })
hi(0, "CursorColumn", { bg = "#241b13" })
hi(0, "CursorLine", { bg = "#241b13" })
hi(0, "CursorLineNr", { bg = "#241b13", fg = "#766454" })
hi(0, "DapUIBreakpointsCurrentLine", { bold = true, fg = "#9c4473" })
hi(0, "DapUIBreakpointsDisabledLine", { fg = "#372b20" })
hi(0, "DapUIBreakpointsInfo", { fg = "#9c4473" })
hi(0, "DapUIBreakpointsLine", { link = "DapUILineNumber" })
hi(0, "DapUIBreakpointsPath", { fg = "#739c44" })
hi(0, "DapUICurrentFrameName", { link = "DapUIBreakpointsCurrentLine" })
hi(0, "DapUIDecoration", { fg = "#739c44" })
hi(0, "DapUIEndofBuffer", { link = "EndOfBuffer" })
hi(0, "DapUIFloatBorder", { fg = "#739c44" })
hi(0, "DapUIFloatNormal", { link = "NormalFloat" })
hi(0, "DapUIFrameName", { link = "Normal" })
hi(0, "DapUILineNumber", { fg = "#739c44" })
hi(0, "DapUIModifiedValue", { bold = true, fg = "#739c44" })
hi(0, "DapUINormal", { link = "Normal" })
hi(0, "DapUINormalNC", { link = "Normal" })
hi(0, "DapUIPlayPause", { fg = "#9c4473" })
hi(0, "DapUIPlayPauseNC", { fg = "#9c4473" })
hi(0, "DapUIRestart", { fg = "#9c4473" })
hi(0, "DapUIRestartNC", { fg = "#9c4473" })
hi(0, "DapUIScope", { fg = "#739c44" })
hi(0, "DapUISource", { fg = "#449c6d" })
hi(0, "DapUIStepBack", { fg = "#739c44" })
hi(0, "DapUIStepBackNC", { fg = "#739c44" })
hi(0, "DapUIStepInto", { fg = "#739c44" })
hi(0, "DapUIStepIntoNC", { fg = "#739c44" })
hi(0, "DapUIStepOut", { fg = "#739c44" })
hi(0, "DapUIStepOutNC", { fg = "#739c44" })
hi(0, "DapUIStepOver", { fg = "#739c44" })
hi(0, "DapUIStepOverNC", { fg = "#739c44" })
hi(0, "DapUIStop", { fg = "#44739c" })
hi(0, "DapUIStopNC", { fg = "#44739c" })
hi(0, "DapUIStoppedThread", { fg = "#739c44" })
hi(0, "DapUIThread", { fg = "#9c4473" })
hi(0, "DapUIType", { fg = "#449c6d" })
hi(0, "DapUIUnavailable", { fg = "#372b20" })
hi(0, "DapUIUnavailableNC", { fg = "#372b20" })
hi(0, "DapUIValue", { link = "Normal" })
hi(0, "DapUIVariable", { link = "Normal" })
hi(0, "DapUIWatchesEmpty", { fg = "#44739c" })
hi(0, "DapUIWatchesError", { fg = "#44739c" })
hi(0, "DapUIWatchesValue", { fg = "#9c4473" })
hi(0, "DapUIWinSelect", { bold = true, fg = "#739c44" })
hi(0, "Debug", { fg = "#44739c" })
hi(0, "Define", { fg = "#449c6d" })
hi(0, "Delimiter", { fg = "#449c99" })
hi(0, "DiagnosticError", { fg = "#44739c" })
hi(0, "DiagnosticHint", { fg = "#9c6d44" })
hi(0, "DiagnosticInfo", { fg = "#739c44" })
hi(0, "DiagnosticUnderlineError", { sp = "#44739c", undercurl = true })
hi(0, "DiagnosticUnderlineHint", { sp = "#9c6d44", undercurl = true })
hi(0, "DiagnosticUnderlineInformation", { sp = "#449c99", undercurl = true })
hi(0, "DiagnosticUnderlineWarn", { sp = "#449c6d", undercurl = true })
hi(0, "DiagnosticUnderlineWarning", { sp = "#449c6d", undercurl = true })
hi(0, "DiagnosticWarn", { fg = "#449c6d" })
hi(0, "DiffAdd", { bg = "#120d09", fg = "#9c4473" })
hi(0, "DiffAdded", { bg = "#120d09", fg = "#9c4473" })
hi(0, "DiffChange", { bg = "#120d09", fg = "#4b3c2e" })
hi(0, "DiffDelete", { bg = "#120d09", fg = "#44739c" })
hi(0, "DiffFile", { bg = "#120d09", fg = "#44739c" })
hi(0, "DiffLine", { bg = "#120d09", fg = "#739c44" })
hi(0, "DiffNewFile", { bg = "#120d09", fg = "#9c4473" })
hi(0, "DiffRemoved", { bg = "#120d09", fg = "#44739c" })
hi(0, "DiffText", { bg = "#120d09", fg = "#739c44" })
hi(0, "Directory", { fg = "#739c44" })
hi(0, "Error", { bg = "#120d09", fg = "#44739c" })
hi(0, "ErrorMsg", { bg = "#120d09", fg = "#44739c" })
hi(0, "Exception", { fg = "#44739c" })
hi(0, "Float", { fg = "#44479c" })
hi(0, "FloatBorder", { bg = "#120d09", fg = "#8f7c6d" })
hi(0, "FoldColumn", { bg = "#120d09", fg = "#9c6d44" })
hi(0, "Folded", { bg = "#241b13", fg = "#4b3c2e" })
hi(0, "Function", { fg = "#739c44" })
hi(0, "FzfLuaBufFlagAlt", { fg = "#98f5ff" })
hi(0, "FzfLuaBufFlagCur", { fg = "#ff4040" })
hi(0, "FzfLuaBufName", { fg = "#ffbbff" })
hi(0, "FzfLuaBufNr", { fg = "#ffebcd" })
hi(0, "FzfLuaHeaderBind", { fg = "#ffebcd" })
hi(0, "FzfLuaHeaderText", { fg = "#ff4040" })
hi(0, "FzfLuaLiveSym", { fg = "#ff4040" })
hi(0, "FzfLuaPathColNr", { fg = "#98f5ff" })
hi(0, "FzfLuaPathLineNr", { fg = "#90ee90" })
hi(0, "FzfLuaTabMarker", { bold = true, fg = "#ffebcd" })
hi(0, "FzfLuaTabTitle", { bold = true, fg = "#b0e2ff" })
hi(0, "GitGutterAdd", { bg = "#120d09", fg = "#9c4473" })
hi(0, "GitGutterChange", { bg = "#120d09", fg = "#739c44" })
hi(0, "GitGutterChangeDelete", { bg = "#120d09", fg = "#449c6d" })
hi(0, "GitGutterDelete", { bg = "#120d09", fg = "#44739c" })
hi(0, "IblIndent", { fg = "#372b20", nocombine = true })
hi(0, "IblScope", { fg = "#766454", nocombine = true })
hi(0, "IblWhitespace", { link = "Whitespace" })
hi(0, "Identifier", { fg = "#44739c" })
hi(0, "IlluminatedWordRead", { sp = "#766454", underline = true })
hi(0, "IlluminatedWordText", { sp = "#766454", underline = true })
hi(0, "IlluminatedWordWrite", { sp = "#766454", underline = true })
hi(0, "IncSearch", { bg = "#44479c", fg = "#241b13" })
hi(0, "Include", { fg = "#739c44" })
hi(0, "IndentBlanklineChar", { fg = "#372b20", nocombine = true })
hi(0, "IndentBlanklineContextChar", { fg = "#766454", nocombine = true })
hi(0, "Italic", { italic = true })
hi(0, "Keyword", { fg = "#449c6d" })
hi(0, "Label", { fg = "#6d449c" })
hi(0, "LineNr", { bg = "#120d09", fg = "#766454" })
hi(0, "LspDiagnosticsDefaultError", { link = "DiagnosticError" })
hi(0, "LspDiagnosticsDefaultHint", { link = "DiagnosticHint" })
hi(0, "LspDiagnosticsDefaultInformation", { link = "DiagnosticInfo" })
hi(0, "LspDiagnosticsDefaultWarning", { link = "DiagnosticWarn" })
hi(0, "LspDiagnosticsUnderlineError", { link = "DiagnosticUnderlineError" })
hi(0, "LspDiagnosticsUnderlineHint", { link = "DiagnosticUnderlineHint" })
hi(0, "LspDiagnosticsUnderlineInformation", { link = "DiagnosticUnderlineInformation" })
hi(0, "LspDiagnosticsUnderlineWarning", { link = "DiagnosticUnderlineWarning" })
hi(0, "LspInlayHint", { fg = "#4b3c2e", italic = true })
hi(0, "LspReferenceRead", { sp = "#766454", underline = true })
hi(0, "LspReferenceText", { sp = "#766454", underline = true })
hi(0, "LspReferenceWrite", { sp = "#766454", underline = true })
hi(0, "Macro", { fg = "#44739c" })
hi(0, "MatchParen", { bg = "#4b3c2e" })
hi(0, "MiniCompletionActiveParameter", { link = "CursorLine" })
hi(0, "ModeMsg", { fg = "#9c4473" })
hi(0, "MoreMsg", { fg = "#9c4473" })
hi(0, "NonText", { fg = "#4b3c2e" })
hi(0, "Normal", { bg = "#120d09", fg = "#8f7c6d" })
hi(0, "NormalFloat", { bg = "#120d09", fg = "#8f7c6d" })
hi(0, "NormalNC", { bg = "#120d09", fg = "#8f7c6d" })
hi(0, "NotifyDEBUGBody", { link = "Normal" })
hi(0, "NotifyDEBUGBorder", { fg = "#9c6d44" })
hi(0, "NotifyDEBUGIcon", { fg = "#9c6d44" })
hi(0, "NotifyDEBUGTitle", { fg = "#9c6d44" })
hi(0, "NotifyERRORBody", { link = "Normal" })
hi(0, "NotifyERRORBorder", { fg = "#44739c" })
hi(0, "NotifyERRORIcon", { fg = "#44739c" })
hi(0, "NotifyERRORTitle", { fg = "#44739c" })
hi(0, "NotifyINFOBody", { link = "Normal" })
hi(0, "NotifyINFOBorder", { fg = "#8f7c6d" })
hi(0, "NotifyINFOIcon", { fg = "#8f7c6d" })
hi(0, "NotifyINFOTitle", { fg = "#8f7c6d" })
hi(0, "NotifyTRACEBody", { link = "Normal" })
hi(0, "NotifyTRACEBorder", { fg = "#9c6d44" })
hi(0, "NotifyTRACEIcon", { fg = "#9c6d44" })
hi(0, "NotifyTRACETitle", { fg = "#9c6d44" })
hi(0, "NotifyWARNBody", { link = "Normal" })
hi(0, "NotifyWARNBorder", { fg = "#449c6d" })
hi(0, "NotifyWARNIcon", { fg = "#449c6d" })
hi(0, "NotifyWARNTitle", { fg = "#449c6d" })
hi(0, "Number", { fg = "#44479c" })
hi(0, "NvimInternalError", { bg = "#44739c", fg = "#120d09" })
hi(0, "Operator", { fg = "#449c6d" })
hi(0, "Pmenu", { bg = "#241b13", fg = "#8f7c6d" })
hi(0, "PmenuSel", { bg = "#8f7c6d", fg = "#241b13" })
hi(0, "PreProc", { fg = "#6d449c" })
hi(0, "Question", { fg = "#739c44" })
hi(0, "QuickFixLine", { bg = "#241b13" })
hi(0, "Repeat", { fg = "#6d449c" })
hi(0, "Search", { bg = "#6d449c", fg = "#241b13" })
hi(0, "SignColumn", { bg = "#120d09", fg = "#766454" })
hi(0, "Special", { fg = "#9c6d44" })
hi(0, "SpecialChar", { fg = "#449c99" })
hi(0, "SpecialKey", { fg = "#4b3c2e" })
hi(0, "SpellBad", { sp = "#44739c", undercurl = true })
hi(0, "SpellCap", { sp = "#739c44", undercurl = true })
hi(0, "SpellLocal", { sp = "#9c6d44", undercurl = true })
hi(0, "SpellRare", { sp = "#449c6d", undercurl = true })
hi(0, "Statement", { fg = "#44739c" })
hi(0, "StatusLine", { bg = "#372b20", fg = "#8f7c6d" })
hi(0, "StatusLineNC", { bg = "#241b13", fg = "#766454" })
hi(0, "StorageClass", { fg = "#6d449c" })
hi(0, "String", { fg = "#9c4473" })
hi(0, "Structure", { fg = "#449c6d" })
hi(0, "Substitute", { bg = "#6d449c", fg = "#241b13" })
hi(0, "TSAnnotation", { fg = "#449c99" })
hi(0, "TSAttribute", { fg = "#6d449c" })
hi(0, "TSBoolean", { fg = "#44479c" })
hi(0, "TSCharacter", { fg = "#44739c" })
hi(0, "TSComment", { fg = "#4b3c2e", italic = true })
hi(0, "TSConditional", { fg = "#449c6d" })
hi(0, "TSConstBuiltin", { fg = "#44479c", italic = true })
hi(0, "TSConstMacro", { fg = "#44739c" })
hi(0, "TSConstant", { fg = "#44479c" })
hi(0, "TSConstructor", { fg = "#739c44" })
hi(0, "TSCurrentScope", { bold = true })
hi(0, "TSDefinition", { sp = "#766454", underline = true })
hi(0, "TSDefinitionUsage", { sp = "#766454", underline = true })
hi(0, "TSEmphasis", { fg = "#44479c", italic = true })
hi(0, "TSError", { fg = "#44739c" })
hi(0, "TSException", { fg = "#44739c" })
hi(0, "TSField", { fg = "#8f7c6d" })
hi(0, "TSFloat", { fg = "#44479c" })
hi(0, "TSFuncBuiltin", { fg = "#739c44", italic = true })
hi(0, "TSFuncMacro", { fg = "#44739c" })
hi(0, "TSFunction", { fg = "#739c44" })
hi(0, "TSInclude", { fg = "#739c44" })
hi(0, "TSKeyword", { fg = "#449c6d" })
hi(0, "TSKeywordFunction", { fg = "#449c6d" })
hi(0, "TSKeywordOperator", { fg = "#449c6d" })
hi(0, "TSLabel", { fg = "#6d449c" })
hi(0, "TSLiteral", { fg = "#44479c" })
hi(0, "TSMethod", { fg = "#739c44" })
hi(0, "TSNamespace", { fg = "#44739c" })
hi(0, "TSNone", { fg = "#8f7c6d" })
hi(0, "TSNumber", { fg = "#44479c" })
hi(0, "TSOperator", { fg = "#8f7c6d" })
hi(0, "TSParameter", { fg = "#8f7c6d" })
hi(0, "TSParameterReference", { fg = "#8f7c6d" })
hi(0, "TSProperty", { fg = "#8f7c6d" })
hi(0, "TSPunctBracket", { fg = "#8f7c6d" })
hi(0, "TSPunctDelimiter", { fg = "#449c99" })
hi(0, "TSPunctSpecial", { fg = "#449c99" })
hi(0, "TSRepeat", { fg = "#449c6d" })
hi(0, "TSStrike", { fg = "#120d09", strikethrough = true })
hi(0, "TSString", { fg = "#9c4473" })
hi(0, "TSStringEscape", { fg = "#9c6d44" })
hi(0, "TSStringRegex", { fg = "#9c6d44" })
hi(0, "TSStrong", { bold = true })
hi(0, "TSSymbol", { fg = "#9c4473" })
hi(0, "TSTag", { fg = "#44739c" })
hi(0, "TSTagDelimiter", { fg = "#449c99" })
hi(0, "TSText", { fg = "#8f7c6d" })
hi(0, "TSTitle", { fg = "#739c44" })
hi(0, "TSType", { fg = "#6d449c" })
hi(0, "TSTypeBuiltin", { fg = "#6d449c", italic = true })
hi(0, "TSURI", { fg = "#44479c", underline = true })
hi(0, "TSUnderline", { fg = "#120d09", underline = true })
hi(0, "TSVariable", { fg = "#44739c" })
hi(0, "TSVariableBuiltin", { fg = "#44739c", italic = true })
hi(0, "TabLine", { bg = "#241b13", fg = "#4b3c2e" })
hi(0, "TabLineFill", { bg = "#241b13", fg = "#4b3c2e" })
hi(0, "TabLineSel", { bg = "#241b13", fg = "#9c4473" })
hi(0, "Tag", { fg = "#6d449c" })
hi(0, "TelescopeBorder", { bg = "#100b08", fg = "#100b08" })
hi(0, "TelescopeNormal", { bg = "#100b08" })
hi(0, "TelescopePreviewLine", { bg = "#241b13" })
hi(0, "TelescopePreviewTitle", { bg = "#9c4473", fg = "#201811" })
hi(0, "TelescopePromptBorder", { bg = "#31261c", fg = "#31261c" })
hi(0, "TelescopePromptNormal", { bg = "#31261c", fg = "#8f7c6d" })
hi(0, "TelescopePromptPrefix", { bg = "#31261c", fg = "#44739c" })
hi(0, "TelescopePromptTitle", { bg = "#44739c", fg = "#201811" })
hi(0, "TelescopeResultsTitle", { bg = "#100b08", fg = "#100b08" })
hi(0, "TelescopeSelection", { bg = "#31261c" })
hi(0, "TermCursor", { bg = "#8f7c6d", fg = "#120d09" })
hi(0, "TermCursorNC", { bg = "#8f7c6d", fg = "#120d09" })
hi(0, "Title", { fg = "#739c44" })
hi(0, "Todo", { bg = "#241b13", fg = "#6d449c" })
hi(0, "TooLong", { fg = "#44739c" })
hi(0, "TreesitterContext", { bg = "#241b13", italic = true })
hi(0, "Type", { fg = "#6d449c" })
hi(0, "Typedef", { fg = "#6d449c" })
hi(0, "Underlined", { fg = "#44739c" })
hi(0, "User1", { bg = "#372b20", fg = "#44739c" })
hi(0, "User2", { bg = "#372b20", fg = "#449c6d" })
hi(0, "User3", { bg = "#372b20", fg = "#8f7c6d" })
hi(0, "User4", { bg = "#372b20", fg = "#9c6d44" })
hi(0, "User5", { bg = "#372b20", fg = "#8f7c6d" })
hi(0, "User6", { bg = "#241b13", fg = "#8f7c6d" })
hi(0, "User7", { bg = "#372b20", fg = "#8f7c6d" })
hi(0, "User8", { bg = "#372b20", fg = "#120d09" })
hi(0, "User9", { bg = "#372b20", fg = "#120d09" })
hi(0, "VertSplit", { bg = "#120d09", fg = "#8f7c6d" })
hi(0, "Visual", { bg = "#372b20" })
hi(0, "VisualNOS", { fg = "#44739c" })
hi(0, "WarningMsg", { fg = "#44739c" })
hi(0, "WildMenu", { bg = "#6d449c", fg = "#44739c" })
hi(0, "WinBar", { fg = "#8f7c6d" })
hi(0, "WinBarNC", { fg = "#766454" })
hi(0, "gitcommitBranch", { bold = true, fg = "#44479c" })
hi(0, "gitcommitComment", { fg = "#4b3c2e" })
hi(0, "gitcommitDiscarded", { fg = "#4b3c2e" })
hi(0, "gitcommitDiscardedFile", { bold = true, fg = "#44739c" })
hi(0, "gitcommitDiscardedType", { fg = "#739c44" })
hi(0, "gitcommitHeader", { fg = "#449c6d" })
hi(0, "gitcommitOverflow", { fg = "#44739c" })
hi(0, "gitcommitSelected", { fg = "#4b3c2e" })
hi(0, "gitcommitSelectedFile", { bold = true, fg = "#9c4473" })
hi(0, "gitcommitSelectedType", { fg = "#739c44" })
hi(0, "gitcommitSummary", { fg = "#9c4473" })
hi(0, "gitcommitUnmergedFile", { bold = true, fg = "#44739c" })
hi(0, "gitcommitUnmergedType", { fg = "#739c44" })
hi(0, "gitcommitUntracked", { fg = "#4b3c2e" })
hi(0, "gitcommitUntrackedFile", { fg = "#6d449c" })
hi(0, "lCursor", { bg = "#8f7c6d", fg = "#120d09" })
hi(0, "rainbowcol1", { fg = "#aa998b" })
hi(0, "rainbowcol2", { fg = "#44479c" })
hi(0, "rainbowcol3", { fg = "#6d449c" })
hi(0, "rainbowcol4", { fg = "#cabeb3" })
hi(0, "rainbowcol5", { fg = "#9c6d44" })
hi(0, "rainbowcol6", { fg = "#739c44" })
hi(0, "rainbowcol7", { fg = "#449c6d" })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#120d09"
g.terminal_color_1 = "#44739c"
g.terminal_color_2 = "#9c4473"
g.terminal_color_3 = "#6d449c"
g.terminal_color_4 = "#739c44"
g.terminal_color_5 = "#449c6d"
g.terminal_color_6 = "#9c6d44"
g.terminal_color_7 = "#8f7c6d"
g.terminal_color_8 = "#4b3c2e"
g.terminal_color_9 = "#44739c"
g.terminal_color_10 = "#9c4473"
g.terminal_color_11 = "#6d449c"
g.terminal_color_12 = "#739c44"
g.terminal_color_13 = "#449c6d"
g.terminal_color_14 = "#9c6d44"
g.terminal_color_15 = "#cabeb3"
