node.rules = [
    {
        matches = [ { node.name = "~bluez_output.*" } ]
        actions = {
            update-props = {
                # Stops the "reconnecting alone" issue during silence
                session.suspend-on-idle = false
            }
        }
    }
]
