# starship config for thyme
# https://github.com/chenhao-ye/thyme
# modified by Yushi_61

add_newline = true
format='''# $username($hostname) at $directory ([\[$git_branch(:$git_commit)(:$git_status)(:$git_state)\]](yellow))$line_break$character'''
right_format = '''($jobs)($status)'''

[username]
format = '[$user](blue)'
show_always = true

[hostname]
format = '[@$hostname](cyan)'

[character]
success_symbol = '\$(bold green)'
error_symbol = '\$(bold red)'

[directory]
format = '[$path]($style)[$read_only]($read_only_style)'
style = 'green'
truncation_length = 6
truncate_to_repo = false
truncation_symbol = '.../'

[git_branch]
format = '[$branch](yellow)'

[git_commit]
format = '[$hash](yellow)'

[git_status]
format = '[$all_status$ahead_behind](yellow)'

[git_state]
format = '[$state($progress_current/$progress_total)](yellow)'

[line_break]
disabled = false

[status]
format = '[\[$status(:$common_meaning)(:$signal_name)\]](red)'
disabled = false

[jobs]
format = '[\[$symbol(:$number)\]](cyan)'
symbol = '⚙'
symbol_threshold = 1
number_threshold = 2
