# Configuration for Starship prompt
# Clean, simple, compatible and meaningful.
# Tested on Linux, Unix and Windows under ANSI colors.
# It is recommended to use with a dark background.
# Colors: black, red, green, yellow, *blue, magenta, cyan, and white.
#
# Mar 2013 Yad Smood

# VCS
[vcs]
  format = "on"
  style = "white"
[vcs.status]
  unstaged = " %{red.bold}x"
  staged = " %{green.bold}o"

# Git info
[git]
  format = "git"
  prefix = ":"
  style = "cyan"
  suffix = ""
  disabled = false

# HG info
[hg]
  format = "hg"
  prefix = ":"
  style = "cyan"
  suffix = ""
  disabled = false

# Prompt format:

# PRIVILEGES USER @ MACHINE in DIRECTORY on git:BRANCH STATE [TIME] C:LAST_EXIT_CODE
# $ COMMAND

# For example:

# % ys @ ys-mbp in ~/.oh-my-zsh on git:master x [21:47:42] C:0
# $
[prompt]
  format = """
# %B%F{blue}#%f
%(!.%B%B%F{yellow}%n%f%b.%B%F{cyan}%n%f) %F{white}@ %F{green}%m %F{white}in %B%F{yellow}%~%f
$vcs
%F{white}[%D %*] $exit_code
%F{red}%b """

